### ISSUE TITLE
Questions about chinese font "Kaiti"

### ISSUE THREAD

**Issue by fsZhuangB** [geekplux/hexo-theme-typing#36]
Hello, first of all thank you about creating this great theme for us.
And now the question is : it's weird to find my blog's chinese font cannot display in the right form because they're good 3 days ago. [I wrote a comment in your blog today(2018/12/18)](https://geekplux.com/2018/09/26/blog-history), and I left a screenshot there, maybe you still remember.  **The characters can be seen, but they didn't display as Kaiti, and I don't know what font they are :(**
I use the default "Kaiti" the same as your own [blog](https://geekplux.com/archives/). I never changed fonts before. 

My thought: 
- First, i think browser didn't render the font, so I use other browser(firefox), but the problem is still here.
- Then I think it's my Mac's problem,  I use my iPhone to test my site, but I think it's not my mac's fault.
- I also change the css file in the **source.css**, and it didn't work, too. (I didn't forget to **make css**:)

So it's hard for me myself to solve this problem alone, could you please give me some advice? Thank you very much!  (my browser and my computer's os: **chrome,  macOS high sierra**)

**Comment by fsZhuangB** [comment]
The chinese font of my blog is now like this: 
![image](https://user-images.githubusercontent.com/20835791/50153027-2a88c300-0300-11e9-85d2-5513816e0276.png)
And they‘re not Kaiti
![image](https://user-images.githubusercontent.com/20835791/50153262-dfbb7b00-0300-11e9-973a-2a3286d7aebe.png)

**Comment by geekplux** [comment]
Thanks for the report. The font `baskervile` is right in front of other fonts, you can find it in `source.css`:

```css
body {
  font-family: Baskerville, "Times New Roman", "Liberation Serif", STFangsong, FangSong, FangSong_GB2312, "CWTEX\-F", serif;
  font-size: 20px;
}

h1, h2, h3, h4, h5, h6 {
  font-family: Baskerville, Georgia, "Liberation Serif", "Kaiti SC", STKaiti, "AR PL UKai CN", "AR PL UKai HK", "AR PL UKai TW", "AR PL UKai TW MBE", "AR PL KaitiM GB", KaiTi, KaiTi_GB2312, DFKai-SB, "TW\-Kai", serif;
}
```

and only title would be `Kaiti`.

Anything includes fonts is like usual in my Macbook and iPhone, you'd better check your font whether installed on your computer, maybe.
